name: Scrape

on:
  schedule:
    - cron: "0 8 * * *" # 8AM everyday UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install notebook requests bs4
    - name: Run scraper
      run: jupyter execute scrape.ipynb
      
    - name: Add and commit
      run: |
        git add .
        git config user.name "Automagic"
        git config user.email "actions@users.noreply.github.com"
        git commit -m "moar data" 
    - name: Push
      run: git push
